if(process.env.ASAY_E2E_LOCAL!=='1')throw new Error('Run only against an isolated local test database with ASAY_E2E_LOCAL=1. This test replaces fixture data.');
const {chromium}=require(process.env.ASAY_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs');
const path=require('path');
const repo=path.resolve(__dirname,'..');
const php=process.env.ASAY_PHP_BIN||'php';const crypto=require('crypto');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const password=crypto.randomBytes(24).toString('base64url');
 await page.goto('http://127.0.0.1:8080/install.php');
 console.log('Installer status',await page.title());
 require('child_process').execFileSync(php,['-r',`require '${repo.replaceAll("'","\\'")}/app/bootstrap.php'; $p=trim(stream_get_contents(STDIN)); db()->prepare('UPDATE users SET password_hash=? WHERE email=?')->execute([password_hash($p,PASSWORD_DEFAULT),'test@example.invalid']);`],{input:password});
 await page.goto('http://127.0.0.1:8080/login.php');
 await page.locator('input[name=email]').fill('test@example.invalid');await page.locator('input[name=password]').fill(password);
 await page.locator('form button').click();await page.waitForURL('**/index.php');await page.waitForFunction(()=>currentSessionUser?.email==='test@example.invalid');
 console.log('Logged in',await page.title());
 await page.evaluate(()=>go('settings'));await page.evaluate(()=>showSettingsCategory('tags'));
 await page.locator('#catalogTagName').fill('Test Etiketi');await page.locator('#catalogTagCategory').fill('Müşteri');await page.locator('#catalogTagSave').click();
 await page.waitForFunction(()=>document.querySelector('#settingsTagList').textContent.includes('Test Etiketi'));
 await page.reload();await page.waitForFunction(()=>currentSessionUser?.email==='test@example.invalid');await page.evaluate(()=>{go('settings');showSettingsCategory('tags')});
 await page.waitForFunction(()=>document.querySelector('#settingsTagList').textContent.includes('Test Etiketi'));
 console.log('PASS catalog persisted after reload');
 fs.mkdirSync('/workspace/artifacts',{recursive:true});await page.evaluate(()=>document.querySelectorAll('.toast').forEach(e=>e.remove()));await page.screenshot({animations:'disabled',path:'/workspace/artifacts/ayarlar-etiketler.png',fullPage:true});
 const assert=require('assert/strict');
 const seedOk=await page.evaluate(async()=>{
  state.accounts=[{id:1,partyKey:'customer-1',type:'customer',name:'Test Müşteri',currency:'EUR',requestOpen:1000,total:0,tags:['Test Etiketi'],entries:[{date:todayISO(),ref:'RFQ-TEST',desc:'Açılış alacağı',debit:1000,credit:0}]},{id:2,partyKey:'customer-1',type:'customer',name:'Test Müşteri',currency:'USD',requestOpen:0,total:0,tags:['İkinci Etiket'],entries:[]},{id:3,partyKey:'supplier-1',type:'supplier',name:'Test Tedarikçi',currency:'EUR',requestOpen:-600,total:0,tags:[],entries:[{date:todayISO(),ref:'RFQ-TEST',desc:'Açılış borcu',debit:0,credit:600}]}];
  state.cashAccounts=[{id:1,name:'Test EUR Banka',type:'Banka',currency:'EUR',balance:0,openingBalance:0}];
  state.requests=[{id:1,no:'RFQ-TEST',title:'Test Talep',customer:'Test Müşteri',customerPartyKey:'customer-1',currency:'EUR',status:'won',country:'Türkiye',deadline:todayISO(),items:[{id:1,name:'Test Ürün',qty:10,unit:'Adet'}],customerQuote:{no:'Q-TEST',total:1000,status:'Kazanıldı',items:[{id:1,name:'Test Ürün',qty:10,unit:'Adet',sale:100,total:1000}]}},{id:2,no:'RFQ-IPTAL',title:'İptal Testi',customer:'Test Müşteri',currency:'EUR',status:'cancelled',items:[]},{id:3,no:'RFQ-KAYIP',title:'Kayıp Testi',customer:'Test Müşteri',currency:'EUR',status:'lost',items:[]}];
  state.orders=[{id:1,no:'ORD-TEST',requestId:1,customer:'Test Müşteri',currency:'EUR',total:1000,customerPaid:0,customerDue:1000,open:true,receivableOpened:true,paymentSchedule:[{label:'Peşin',percent:30,amount:300,paid:0,due:300},{label:'Teslim',percent:70,amount:700,paid:0,due:700}],pos:[{id:1,no:'PO-TEST',supplier:'Test Tedarikçi',currency:'EUR',total:600,paid:0,due:600,status:'Hazırlanıyor',items:[{itemId:1,qty:10}]}],deliveryBatches:[]}];
  state.cash=[];state.documents=[];return await saveDbState(true);
 });assert(seedOk,'seed persistence');
 await page.evaluate(()=>{go('requests');document.getElementById('requestCompletionFilter').value='active';renderRequests()});
 assert.equal(await page.locator('#requestList .request-card').count(),1);
 await page.selectOption('#requestCompletionFilter','cancelled');assert.equal(await page.locator('#requestList .request-card').count(),1);assert.match(await page.locator('#requestList').innerText(),/RFQ-IPTAL/);
 await page.selectOption('#requestCompletionFilter','lost');assert.match(await page.locator('#requestList').innerText(),/RFQ-KAYIP/);
 await page.selectOption('#requestCompletionFilter','all');assert.equal(await page.locator('#requestList .request-card').count(),3);console.log('PASS active / cancelled / lost / all filters');
 await page.evaluate(()=>{go('accounts');openAccountTagManager('customer-1');tagWorking=['Test Etiketi','İkinci Etiket'];return saveTags()});
 await page.reload();await page.waitForFunction(()=>state.accounts.length===3);
 const tags=await page.evaluate(()=>groupedAccounts().find(g=>g.partyKey==='customer-1').profile.tags);assert.deepEqual(tags.sort(),['Test Etiketi','İkinci Etiket'].sort());
 await page.evaluate(()=>go('accounts'));assert.match(await page.locator('#accountCards').innerText(),/İkinci Etiket/);console.log('PASS customer tags persisted across currencies and reload');
 async function op(input){console.log('Running',input.action);const timer=setTimeout(async()=>{console.log('Pending operation UI',await page.locator('.modal-backdrop.show').innerText().catch(()=>''));await page.evaluate(()=>document.querySelectorAll('.toast').forEach(e=>e.remove()));await page.screenshot({animations:'disabled',path:'/workspace/artifacts/pending.png'});},6000);const out=await page.evaluate(async input=>{const ok=await runServerOperation({...input,idempotencyKey:makeIdempotencyKey()});return {ok,error:window.lastDbSaveError||document.querySelector('.toast.warn')?.textContent}},input);clearTimeout(timer);assert(out.ok,JSON.stringify(out));}
 await op({action:'prepayment',orderId:1,amount:400,bankId:1,fxRate:1,fxRateConfirmed:true,description:'Test tahsilatı'});
 let finance=await page.evaluate(()=>({paid:state.orders[0].customerPaid,due:state.orders[0].customerDue,plan:customerPaymentScheduleDisplay(state.orders[0]),bank:state.cashAccounts[0].balance,jid:state.cash.find(c=>c.kind==='customer_prepayment').journalId}));
 assert.equal(finance.paid,400);assert.equal(finance.due,600);assert.equal(finance.bank,400);assert.equal(finance.plan[0].paid,300);assert.equal(finance.plan[1].paid,100);console.log('PASS real receipt allocated to payment schedule');
 await op({action:'finance_customer_receipt_update',journalId:finance.jid,amount:250,bankId:1,date:'2026-10-06',description:'Düzenlenmiş test tahsilatı',fxRate:1,fxRateConfirmed:true});
 finance=await page.evaluate(()=>({paid:state.orders[0].customerPaid,due:state.orders[0].customerDue,bank:state.cashAccounts[0].balance,jid:state.cash.find(c=>c.kind==='customer_prepayment').journalId}));assert.equal(finance.paid,250);assert.equal(finance.due,750);assert.equal(finance.bank,250);console.log('PASS receipt edit reconciles order / bank');
 await op({action:'finance_delete',journalId:finance.jid});
 finance=await page.evaluate(()=>({paid:state.orders[0].customerPaid,due:state.orders[0].customerDue,bank:state.cashAccounts[0].balance,plan:customerPaymentScheduleDisplay(state.orders[0])}));assert.equal(finance.paid,0);assert.equal(finance.due,1000);assert.equal(finance.bank,0);assert.equal(finance.plan[0].paid,0);console.log('PASS receipt delete reconciles order / bank / schedule');
 await page.evaluate(async()=>{state.orders[0].deliveryBatches=[{id:1,batchNo:'B-TEST',status:'Teslim Edildi',deliveredDate:'2026-10-06',items:[{itemId:1,qty:10}],customerAmount:1000,customerCollected:0,customerDue:1000,supplierPayments:[],deliveryUndoSnapshot:{}}];return await saveDbState(true)});
 await op({action:'delivery_batch_undo',orderId:1,batchId:1});assert.equal(await page.evaluate(()=>state.orders[0].deliveryBatches[0].status),'Planlandı');console.log('PASS delivery undo');
 await page.evaluate(()=>{go('docs');document.getElementById('docRequestSelect').value=1;syncDocQuoteSelect();document.getElementById('docType').value='offer';renderDocument()});
 const svg='data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="80"><rect width="160" height="80" fill="#2563eb"/><text x="20" y="50" fill="white" font-size="24">ASAY</text></svg>').toString('base64');
 await page.evaluate(svg=>{for(const id of ['pdfLogo','pdfStamp']){const e=document.getElementById(id);e.src=svg;e.style.display='block';e.style.left='160px';e.style.top=(id==='pdfLogo'?90:600)+'px';e.style.right='auto';e.style.bottom='auto';resizePdfAsset(id,160)}},svg);
 await page.waitForFunction(()=>document.getElementById('pdfLogo').complete);
 await page.evaluate(()=>saveCurrentDocument());const did=await page.evaluate(()=>state.documents.at(-1).id);
 await page.evaluate(id=>editSavedDocument(id),did);await page.waitForFunction(()=>editingDocumentId!==null);
 assert.equal(await page.locator('#pdfLogo').count(),1);assert.equal(await page.locator('#pdfLogo').evaluate(e=>e.parentElement.id),'pdfDemo');assert.equal(await page.locator('#pdfLogo').evaluate(e=>e.offsetWidth),160);
 const before=await page.locator('#pdfLogo').boundingBox();await page.mouse.move(before.x+30,before.y+20);await page.mouse.down();await page.mouse.move(before.x+90,before.y+65,{steps:10});await page.mouse.up();
 const pos=await page.locator('#pdfLogo').evaluate(e=>({x:e.offsetLeft,y:e.offsetTop,width:e.offsetWidth}));assert(pos.x>160,'restored logo can drag');await page.evaluate(()=>resizePdfAsset('pdfLogo',200));await page.evaluate(()=>saveCurrentDocument());
 await page.reload();await page.waitForFunction(()=>state.documents.length>0);await page.evaluate(id=>editSavedDocument(id),did);await page.waitForFunction(()=>editingDocumentId!==null);
 assert.equal(await page.locator('#pdfLogo').evaluate(e=>e.offsetWidth),200);
 const savedPos=await page.locator('#pdfLogo').evaluate(e=>({x:e.offsetLeft,y:e.offsetTop}));assert.deepEqual(savedPos,{x:pos.x,y:pos.y});
 const printable=await page.evaluate(()=>({html:printableDocumentHtml(),css:documentPrintCss('portrait',false)}));
 const printPage=await browser.newPage();await printPage.setContent(`<style>${printable.css}</style><div class="page">${printable.html}</div>`);await printPage.emulateMedia({media:'print'});
 const printPos=await printPage.locator('#pdfLogo').evaluate(e=>({x:e.offsetLeft,y:e.offsetTop,width:e.offsetWidth}));assert.deepEqual(printPos,{x:pos.x,y:pos.y,width:200});await printPage.pdf({path:'/workspace/artifacts/evrak-test.pdf',preferCSSPageSize:true});
 console.log('PASS saved logo drag / resize / reload / print coordinate parity');await page.evaluate(()=>document.querySelectorAll('.toast').forEach(e=>e.remove()));await page.screenshot({animations:'disabled',path:'/workspace/artifacts/pdf-studyosu.png',fullPage:true});await printPage.close();


 await op({action:'prepayment',orderId:1,amount:400,bankId:1,fxRate:1,fxRateConfirmed:true,description:'Tedarikçi ödeme testi için tahsilat'});
 await op({action:'cash_movement',mode:'payment',orderId:1,poId:1,poNo:'PO-TEST',partyId:3,bankId:1,amount:100,request:'RFQ-TEST',description:'Test tedarikçi ödemesi',date:'2026-10-01'});
 const supplierFinance=await page.evaluate(()=>({group:orderSupplierFinanceByCurrency(state.orders[0]),history:orderSupplierPaymentRows(state.orders[0]).length,date:orderSupplierPaymentRows(state.orders[0])[0]?.date}));assert.equal(supplierFinance.group.EUR.paid,100);assert.equal(supplierFinance.group.EUR.due,500);assert.equal(supplierFinance.history,1);assert.equal(supplierFinance.date,'01.10.2026');console.log('PASS real supplier payment tracking and history');
 await page.evaluate(()=>go('orders'));await page.evaluate(()=>document.querySelectorAll('.toast').forEach(e=>e.remove()));await page.screenshot({animations:'disabled',path:'/workspace/artifacts/odeme-takibi.png',fullPage:true});
 await op({action:'status_change',requestId:2,status:'collecting',reason:''});assert.equal(await page.evaluate(()=>state.requests.find(r=>r.id===2).status),'collecting');console.log('PASS cancelled request reopen');
 await page.evaluate(()=>{go('docs');document.getElementById('docRequestSelect').value=1;syncDocQuoteSelect();setOrientation('landscape');document.getElementById('docType').value='packing';renderDocument();});
 await page.evaluate(svg=>{const stamp=document.getElementById('pdfStamp');stamp.src=svg;stamp.style.display='block';stamp.style.left='300px';stamp.style.top='400px';stamp.style.right='auto';stamp.style.bottom='auto';resizePdfAsset('pdfStamp',180)},svg);await page.waitForFunction(()=>document.getElementById('pdfStamp').complete);
 const landscape=await page.evaluate(()=>({html:printableDocumentHtml(),css:documentPrintCss('landscape',true)}));const lp=await browser.newPage();await lp.setContent(`<style>${landscape.css}</style><div class="page">${landscape.html}</div>`);await lp.emulateMedia({media:'print'});assert.deepEqual(await lp.locator('#pdfStamp').evaluate(e=>({x:e.offsetLeft,y:e.offsetTop,w:e.offsetWidth})),{x:300,y:400,w:180});await lp.close();console.log('PASS landscape multipage stamp coordinate parity');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{go('settings');showSettingsCategory('tags')});assert(await page.locator('#settingsTags').isVisible());await page.evaluate(()=>document.querySelectorAll('.toast').forEach(e=>e.remove()));await page.screenshot({animations:'disabled',path:'/workspace/artifacts/ayarlar-mobil.png',fullPage:true});console.log('PASS mobile settings category');
 assert.deepEqual(errors,[],'uncaught browser errors');console.log('Page errors',JSON.stringify(errors));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
