<?php
declare(strict_types=1);require_once __DIR__.'/../app/bootstrap.php';require_once __DIR__.'/../app/simple_zip.php';require_login();$in=json_decode(file_get_contents('php://input'),true)?:[];$headers=$in['headers']??[];$rows=$in['rows']??[];$columnWidths=is_array($in['columnWidths']??null)?$in['columnWidths']:[];$title=preg_replace('/[^A-Za-z0-9_-]+/','_',($in['title']??'ASAY_Rapor'));
if(!is_array($headers)||!is_array($rows))json_response(['ok'=>false,'error'=>'Geçersiz rapor verisi'],422);if(count($rows)>20000)json_response(['ok'=>false,'error'=>'XLSX satır sınırı 20.000'],413);
function x($s){return htmlspecialchars((string)$s,ENT_XML1|ENT_QUOTES,'UTF-8');}function col($n){$s='';for($n++;$n>0;$n=intdiv($n-1,26))$s=chr(65+(($n-1)%26)).$s;return $s;}
$tmp=tempnam(sys_get_temp_dir(),'asayxlsx');
if(class_exists('ZipArchive')){$zip=new ZipArchive();$opened=$zip->open($tmp,ZipArchive::OVERWRITE)===true;}
else{$zip=new AsaySimpleZip();$opened=$zip->open($tmp);}
if(!$opened)json_response(['ok'=>false,'error'=>'XLSX oluşturulamadı'],500);
$zip->addFromString('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>');
$zip->addFromString('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
$zip->addFromString('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Rapor" sheetId="1" r:id="rId1"/></sheets></workbook>');
$zip->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
$zip->addFromString('xl/styles.xml','<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font><font><b/><sz val="10"/><name val="Arial"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF163D73"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEAF2FF"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FFD9E2EC"/></left><right style="thin"><color rgb="FFD9E2EC"/></right><top style="thin"><color rgb="FFD9E2EC"/></top><bottom style="thin"><color rgb="FFD9E2EC"/></bottom></border></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="4"><xf fontId="0"/><xf fontId="1" fillId="2" borderId="1" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf fontId="0" borderId="1" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf fontId="2" fillId="3" borderId="1" applyFont="1" applyFill="1" applyBorder="1"/></cellXfs></styleSheet>');
$colCount=max(1,count($headers));$lastCol=col($colCount-1);$cols='';for($i=0;$i<$colCount;$i++){if(isset($columnWidths[$i])&&is_numeric($columnWidths[$i])){$w=max(7,min(60,(float)$columnWidths[$i]));}else{$samples=[(string)($headers[$i]??'')];foreach(array_slice($rows,0,120) as $rr)$samples[]=(string)($rr[$i]??'');$max=0;foreach($samples as $sv)$max=max($max,mb_strlen($sv,'UTF-8'));$w=max(9,min(36,$max+2));}$cols.='<col min="'.($i+1).'" max="'.($i+1).'" width="'.$w.'" customWidth="1"/>';}$xml='<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols>'.$cols.'</cols><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>';$r=1;$all=array_merge([$headers],$rows);foreach($all as $ri=>$row){$isSummary=isset($row[0])&&$row[0]==='ÖZET';$xml.='<row r="'.$r.'"'.($ri===0?' ht="30" customHeight="1"':'').'>';foreach(array_values((array)$row) as $ci=>$v){$ref=col($ci).$r;$style=$ri===0?' s="1"':($isSummary?' s="3"':' s="2"');if(is_numeric($v)&&!preg_match('/^0\d+/',(string)$v))$xml.='<c r="'.$ref.'"'.$style.'><v>'.x($v).'</v></c>';else$xml.='<c r="'.$ref.'" t="inlineStr"'.$style.'><is><t>'.x($v).'</t></is></c>';}$xml.='</row>';$r++;}$xml.='</sheetData><autoFilter ref="A1:'.$lastCol.'1"/></worksheet>';$zip->addFromString('xl/worksheets/sheet1.xml',$xml);$zip->close();audit('report_xlsx_export','report',null,['title'=>$title,'rows'=>count($rows)]);header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$title.'_'.date('Y-m-d').'.xlsx"');header('Content-Length: '.filesize($tmp));readfile($tmp);@unlink($tmp);
